version: "3.8"

networks:
    purple-dev-net:
        driver: bridge

volumes:
    postgresdb:
        driver: local

services:
  db:
    image: postgres
    volumes:
      - postgresdb:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - purple-dev-net